The following steps were followed to create the final submission file 
This model was build on RandomForest classifier reading data from the csv files give in the competition

Step1: Read the train_data.csv with chunk_size=5lakh

Step2: create individual files for each chunk,12 such files were generated

step3: Checked individual dataframes for columns with more than 40% missing values

Step4. All the 12 dataframes have same columns for missing values

step5. Checked individual dataframes for columns with correlations coeff.75

step6. same columns were found in all 12 dataframes for correlation coeff .75

step7. Hence selected one  dataframe and deleted the above columns

step8. Filled nan values with bfill,ffill

step9. Build the model with randomn forest as this gave a better amex_metric

step10. Read the test_data.csv with chunk_size=5lak

step11. followed steps for data imputation as train data

step12.predicted submitted the file

step13.The following procedure gave an amex_metric .477



In [1]:
#-------------------------------------------------------------------------------------------------------------------------------
import pandas as pd                                                 # Importing for panel data analysis
#from pandas_profiling import ProfileReport                          # Import Pandas Profiling (To generate Univariate Analysis)

pd.set_option('display.max_columns', None)                          # Unfolding hidden features if the cardinality is high      
pd.set_option('display.max_colwidth', None)                         # Unfolding the max feature width for better clearity      
pd.set_option('display.max_rows', None)                             # Unfolding hidden data points if the cardinality is high
pd.set_option('mode.chained_assignment', None)                      # Removing restriction over chained assignments operations
pd.set_option('display.float_format', lambda x: '%.5f' % x)         # To suppress scientific notation over exponential values
#-------------------------------------------------------------------------------------------------------------------------------
import numpy as np                                                  # Importing package numpys (For Numerical Python)
#-------------------------------------------------------------------------------------------------------------------------------
import matplotlib.pyplot as plt                                     # Importing pyplot interface using matplotlib
from matplotlib.pylab import rcParams                               # Backend used for rendering and GUI integration                                               
import seaborn as sns                                               # Importin seaborm library for interactive visualization
%matplotlib inline
#-------------------------------------------------------------------------------------------------------------------------------
from sklearn.metrics import accuracy_score                          # For calculating the accuracy for the model
from sklearn.metrics import precision_score                         # For calculating the Precision of the model
from sklearn.metrics import recall_score                            # For calculating the recall of the model
from sklearn.metrics import precision_recall_curve                  # For precision and recall metric estimation
from sklearn.metrics import confusion_matrix                        # For verifying model performance using confusion matrix
from sklearn.metrics import f1_score                                # For Checking the F1-Score of our model  
from sklearn.metrics import roc_curve                               # For Roc-Auc metric estimation
#-------------------------------------------------------------------------------------------------------------------------------
from sklearn.model_selection import train_test_split                # To split the data in training and testing part     
from sklearn.linear_model import LogisticRegression                 # To create the Logistic Regression Model
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score
#-------------------------------------------------------------------------------------------------------------------------------
import warnings                                                     # Importing warning to disable runtime warnings
warnings.filterwarnings("ignore")                                   # Warnings will appear only once


In [2]:
# Create correlation matrix
to_drop=[]
import numpy as np
def drop_corr_columns(df,i):

    corr_matrix = df.corr().abs()

# Select upper triangle of correlation matrix
    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find index of feature columns with correlatgc.collect()ion greater than 0.95
    to_drop = [column for column in upper.columns if any(upper[column] > 0.7)]
    print('columns to drop in ',{i},'dataset',to_drop)
    df1.drop(axis=1,columns= to_drop,inplace=True)
   

In [3]:
#Reading dataset with 500000 rows

df=pd.read_csv('../input/amex-reading-data/data1.csv')



In [4]:
df_target=pd.read_csv('../input/amex-default-prediction/train_labels.csv')

In [5]:
df1=pd.merge(df,df_target,on='customer_ID',how='inner')

In [6]:
list_miss=df1.isnull().sum()/len(df1)

In [7]:
#finding columns with more than 40% missing values
list_missing=[]
for i in range(len(list_miss)):
    if list_miss[i]>0.4 :
        list_missing.append(list_miss.index[i])

In [8]:
list_missing

['D_42',
 'D_49',
 'D_50',
 'D_53',
 'D_56',
 'S_9',
 'B_17',
 'D_66',
 'D_73',
 'D_76',
 'D_77',
 'R_9',
 'D_82',
 'B_29',
 'D_87',
 'D_88',
 'D_105',
 'D_106',
 'R_26',
 'D_108',
 'D_110',
 'D_111',
 'B_39',
 'B_42',
 'D_132',
 'D_134',
 'D_135',
 'D_136',
 'D_137',
 'D_138',
 'D_142']

In [9]:
df1.drop(columns=list_missing,inplace=True)

In [10]:
drop_corr_columns(df1,1)

columns to drop in  {1} dataset ['B_3', 'D_48', 'B_8', 'B_11', 'R_4', 'S_7', 'D_55', 'B_13', 'D_58', 'D_61', 'B_15', 'B_16', 'B_18', 'B_19', 'B_20', 'B_22', 'S_15', 'B_23', 'D_74', 'D_75', 'R_8', 'S_16', 'B_28', 'B_30', 'R_21', 'B_33', 'S_24', 'D_103', 'D_104', 'D_107', 'B_37', 'B_38', 'D_113', 'D_118', 'D_119', 'D_121', 'D_129', 'D_131', 'D_133', 'D_141', 'D_143']


In [11]:
to_drop

[]

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 499999
Columns: 120 entries, Unnamed: 0 to target
dtypes: float64(113), int64(3), object(4)
memory usage: 461.6+ MB


In [13]:
df1.drop('Unnamed: 0',axis=1,inplace=True)

In [14]:
df1.drop('customer_ID',axis=1,inplace=True)

In [15]:
df1.drop('S_2',axis=1,inplace=True)

In [16]:
df1.fillna(method="ffill",inplace=True)


In [17]:
df1.fillna(method="bfill",inplace=True)


In [18]:
df1.isnull().sum()

P_2       0
D_39      0
B_1       0
B_2       0
R_1       0
S_3       0
D_41      0
D_43      0
D_44      0
B_4       0
D_45      0
B_5       0
R_2       0
D_46      0
D_47      0
B_6       0
B_7       0
D_51      0
B_9       0
R_3       0
D_52      0
P_3       0
B_10      0
S_5       0
S_6       0
D_54      0
B_12      0
S_8       0
R_5       0
B_14      0
D_59      0
D_60      0
S_11      0
D_62      0
D_63      0
D_64      0
D_65      0
D_68      0
S_12      0
R_6       0
S_13      0
B_21      0
D_69      0
D_70      0
D_71      0
D_72      0
P_4       0
B_24      0
R_7       0
B_25      0
B_26      0
D_78      0
D_79      0
D_80      0
R_10      0
R_11      0
B_27      0
D_81      0
S_17      0
R_12      0
R_13      0
D_83      0
R_14      0
R_15      0
D_84      0
R_16      0
S_18      0
D_86      0
R_17      0
R_18      0
B_31      0
S_19      0
R_19      0
B_32      0
S_20      0
R_20      0
D_89      0
R_22      0
R_23      0
D_91      0
D_92      0
D_93      0
D_94      0
R_24

In [19]:
df1.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 499999
Data columns (total 117 columns):
 #    Column  Dtype  
---   ------  -----  
 0    P_2     float64
 1    D_39    float64
 2    B_1     float64
 3    B_2     float64
 4    R_1     float64
 5    S_3     float64
 6    D_41    float64
 7    D_43    float64
 8    D_44    float64
 9    B_4     float64
 10   D_45    float64
 11   B_5     float64
 12   R_2     float64
 13   D_46    float64
 14   D_47    float64
 15   B_6     float64
 16   B_7     float64
 17   D_51    float64
 18   B_9     float64
 19   R_3     float64
 20   D_52    float64
 21   P_3     float64
 22   B_10    float64
 23   S_5     float64
 24   S_6     float64
 25   D_54    float64
 26   B_12    float64
 27   S_8     float64
 28   R_5     float64
 29   B_14    float64
 30   D_59    float64
 31   D_60    float64
 32   S_11    float64
 33   D_62    float64
 34   D_63    object 
 35   D_64    object 
 36   D_65    float64
 37   D_68    float64
 38   S_

S_2,D_63,D_64 object type

In [20]:
df1.D_63.unique()

array(['CR', 'CO', 'CL', 'XZ', 'XM', 'XL'], dtype=object)

In [21]:
df1['D_64'] = df1['D_64'].str.replace('-1','R')


Model building

Step 1: one hot encoding

In [22]:
df1_dummies = pd.get_dummies(df1, drop_first=True)


In [23]:
df1_dummies.drop('target',axis=1,inplace=True)

In [24]:
df1_dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500000 entries, 0 to 499999
Columns: 121 entries, P_2 to D_64_U
dtypes: float64(113), int64(1), uint8(7)
memory usage: 442.0 MB


In [25]:
y=df1.target

In [26]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [27]:
X=df1_dummies

In [28]:
X.shape

(500000, 121)

In [29]:
y.shape

(500000,)

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify = y)

print('Training Data Shape:', X_train.shape, y_train.shape)
print('Testing Data Shape:', X_test.shape, y_test.shape)

Training Data Shape: (350000, 121) (350000,)
Testing Data Shape: (150000, 121) (150000,)


In [31]:
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression()

In [32]:
#predicting on train data
y_pred_train = logreg.predict(X_train)

#predicting on test data
y_pred_test = logreg.predict(X_test)

In [33]:

print(confusion_matrix(y_test, y_pred_test))
confusion_matrix.index = ['Actual D','Actual nd']
confusion_matrix.columns = ['Predicted D','Predicted nd']
print(confusion_matrix)
print(classification_report(y_test,y_pred_test))

[[103687   8810]
 [ 11262  26241]]
<function confusion_matrix at 0x7f0bb0fb58c0>
              precision    recall  f1-score   support

           0       0.90      0.92      0.91    112497
           1       0.75      0.70      0.72     37503

    accuracy                           0.87    150000
   macro avg       0.83      0.81      0.82    150000
weighted avg       0.86      0.87      0.86    150000



In [34]:
pred = logreg.predict(X_test)
print('Accuracy score for test data is:', accuracy_score(y_test,pred))

Accuracy score for test data is: 0.8661866666666667


In [35]:
scoreslg = cross_val_score(logreg,X_train,y_train,cv=5,scoring='f1')
print(scoreslg)
print("Average f1")
print(np.mean(scoreslg))

[0.72159712 0.72338021 0.72312219 0.71902352 0.72579597]
Average f1
0.7225838034870973


In [36]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()

dtree.fit(X_train,y_train)
#predicting on train data
y_pred_train = dtree.predict(X_train)

#predicting on test data
y_pred_test = dtree.predict(X_test)

print("Testing Accuracy for dtree")
print(dtree.score(X_test,y_test))

print("Training Accuracy for dtree")
print(dtree.score(X_train,y_train))
print(confusion_matrix(y_test,y_pred_test))
print(classification_report(y_test,y_pred_test))


Testing Accuracy for dtree
0.85598
Training Accuracy for dtree
1.0
[[101694  10803]
 [ 10800  26703]]
              precision    recall  f1-score   support

           0       0.90      0.90      0.90    112497
           1       0.71      0.71      0.71     37503

    accuracy                           0.86    150000
   macro avg       0.81      0.81      0.81    150000
weighted avg       0.86      0.86      0.86    150000



In [37]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score
lr = RandomForestClassifier(n_estimators=10,class_weight='balanced',verbose=True)
lr.fit(X_train,y_train)
print("Training Accuracy")
print(lr.score(X_train,y_train))
print("Testing Accuracy")
print(lr.score(X_test,y_test))
predicted = lr.predict(X_test)
print(confusion_matrix(y_test,predicted))
print(classification_report(y_test,predicted))



[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.5min finished


Training Accuracy


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


0.9936228571428571
Testing Accuracy


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


0.87214


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.9s finished


[[106693   5804]
 [ 13375  24128]]
              precision    recall  f1-score   support

           0       0.89      0.95      0.92    112497
           1       0.81      0.64      0.72     37503

    accuracy                           0.87    150000
   macro avg       0.85      0.80      0.82    150000
weighted avg       0.87      0.87      0.87    150000



In [38]:
scoresdt = cross_val_score(lr,X_train,y_train,cv=5,scoring='f1')
print(scoresdt)
print("Average f1")
print(np.mean(scoresdt))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:  1.2min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_j

[0.70260494 0.70686256 0.70353136 0.69859065 0.70558327]
Average f1
0.7034345564796199


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.3s finished


In [39]:
 y_train_pred_count=lr.predict(X_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.8s finished


In [40]:
def amex_metric_mod(y_true, y_pred):

    labels     = np.transpose(np.array([y_true, y_pred]))
    labels     = labels[labels[:, 1].argsort()[::-1]]
    weights    = np.where(labels[:,0]==0, 20, 1)
    cut_vals   = labels[np.cumsum(weights) <= int(0.04 * np.sum(weights))]
    top_four   = np.sum(cut_vals[:,0]) / np.sum(labels[:,0])

    gini = [0,0]
    for i in [1,0]:
        labels         = np.transpose(np.array([y_true, y_pred]))
        labels         = labels[labels[:, i].argsort()[::-1]]
        weight         = np.where(labels[:,0]==0, 20, 1)
        weight_random  = np.cumsum(weight / np.sum(weight))
        total_pos      = np.sum(labels[:, 0] *  weight)
        cum_pos_found  = np.cumsum(labels[:, 0] * weight)
        lorentz        = cum_pos_found / total_pos
        gini[i]        = np.sum((lorentz - weight_random) * weight)

    return 0.5 * (gini[1]/gini[0] + top_four)
print(amex_metric_mod(y_train, y_train_pred_count)) 

0.9770732728320988


In [41]:
print(amex_metric_mod(y_test, predicted)) 

0.5062304824057255


In [42]:

def create_model(df_test,subm_test):
   
    
    df_test.drop('customer_ID',axis=1,inplace=True)
    df_test.drop('S_2',axis=1,inplace=True)
    df_test.fillna(method='ffill',inplace=True)
    df_test.fillna(method='bfill',inplace=True)
    df_test_dummies=pd.get_dummies(df_test, drop_first=True)
  
    subm_test['pred']=lr.predict(df_test_dummies)
    #print(subm_test.head())
    #subm_test2=subm_test2.append(subm_test1)
    subm_test.to_csv('submssion.csv',mode='a',header=True,index=False)

In [43]:
del_col=['B_3', 'D_48', 'B_8', 'B_11', 'R_4', 'S_7', 'D_55', 'B_13', 'D_58', 'D_61', 'B_15', 'B_16', 'B_18', 'B_19', 'B_20', 'B_22', 'S_15', 'B_23', 'D_74', 'D_75', 'D_77', 'R_8', 'S_16', 'B_28', 'B_30', 'R_21', 'B_33', 'S_24', 'D_103', 'D_104', 'D_107', 'B_37', 'B_38', 'D_113', 'D_118', 'D_119', 'D_121', 'D_129', 'D_131', 'D_133', 'D_141', 'D_143','D_42',
 'D_49',
 'D_50',
 'D_53',
 'D_56',
 'S_9',
 'B_17',
 'D_66',
 'D_73',
 'D_76',
 'D_77',
 'R_9',
 'D_82',
 'B_29',
 'D_87',
 'D_88',
 'D_105',
 'D_106',
 'R_26',
 'D_108',
 'D_110',
 'D_111',
 'B_39',
 'B_42',
 'D_132',
 'D_134',
 'D_135',
 'D_136',
 'D_137',
 'D_138',
 'D_142']


In [44]:
headers = [*pd.read_csv('../input/amex-default-prediction/test_data.csv', nrows=1)]
#cols = list(pd.read_csv("test_data.csv", nrows =1))
print(headers)

['customer_ID', 'S_2', 'P_2', 'D_39', 'B_1', 'B_2', 'R_1', 'S_3', 'D_41', 'B_3', 'D_42', 'D_43', 'D_44', 'B_4', 'D_45', 'B_5', 'R_2', 'D_46', 'D_47', 'D_48', 'D_49', 'B_6', 'B_7', 'B_8', 'D_50', 'D_51', 'B_9', 'R_3', 'D_52', 'P_3', 'B_10', 'D_53', 'S_5', 'B_11', 'S_6', 'D_54', 'R_4', 'S_7', 'B_12', 'S_8', 'D_55', 'D_56', 'B_13', 'R_5', 'D_58', 'S_9', 'B_14', 'D_59', 'D_60', 'D_61', 'B_15', 'S_11', 'D_62', 'D_63', 'D_64', 'D_65', 'B_16', 'B_17', 'B_18', 'B_19', 'D_66', 'B_20', 'D_68', 'S_12', 'R_6', 'S_13', 'B_21', 'D_69', 'B_22', 'D_70', 'D_71', 'D_72', 'S_15', 'B_23', 'D_73', 'P_4', 'D_74', 'D_75', 'D_76', 'B_24', 'R_7', 'D_77', 'B_25', 'B_26', 'D_78', 'D_79', 'R_8', 'R_9', 'S_16', 'D_80', 'R_10', 'R_11', 'B_27', 'D_81', 'D_82', 'S_17', 'R_12', 'B_28', 'R_13', 'D_83', 'R_14', 'R_15', 'D_84', 'R_16', 'B_29', 'B_30', 'S_18', 'D_86', 'D_87', 'R_17', 'R_18', 'D_88', 'B_31', 'S_19', 'R_19', 'B_32', 'S_20', 'R_20', 'R_21', 'B_33', 'D_89', 'R_22', 'R_23', 'D_91', 'D_92', 'D_93', 'D_94', 'R_2

In [45]:
final_col=list ((set(headers) - set (del_col)))

In [46]:
df_testdata = pd.read_csv('../input/amex-default-prediction/test_data.csv', chunksize=500000, iterator=True, usecols =final_col)

In [47]:


for iter_num, chunk in enumerate(df_testdata, 1):
    print(iter_num)
    subm_t=pd.DataFrame(columns=['customer_ID','pred'])
    subm_t["customer_ID"]=  chunk["customer_ID"]
   
    #print(chunk.info())
    #print(subm_t.info())
    create_model(chunk,subm_t)
    


1


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


2


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.2s finished


3


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


4


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


5


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


6


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


7


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


8


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


9


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


10


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


11


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


12


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.2s finished


13


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.2s finished


14


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


15


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


16


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.1s finished


17


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


18


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


19


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.3s finished


20


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


21


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.0s finished


22


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    2.1s finished


23


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    1.5s finished


In [48]:
import gc
gc.collect()

169

In [49]:

df_sub=pd.read_csv('submssion.csv')

In [50]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11363784 entries, 0 to 11363783
Data columns (total 2 columns):
 #   Column       Dtype 
---  ------       ----- 
 0   customer_ID  object
 1   pred         object
dtypes: object(2)
memory usage: 173.4+ MB


In [51]:
df_sub.customer_ID.nunique()

924622

In [52]:
#df.drop(df.loc[df['Stock']=='Yes'].index, inplace=True)
df_sub.drop(df_sub.loc[df_sub['customer_ID']=='customer_ID'].index,inplace=True)

In [53]:
df_sub.customer_ID.nunique()

924621

In [54]:
df_final_sub=df_sub.groupby('customer_ID').tail(1)

In [55]:
df_final_sub.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 924621 entries, 8 to 11363783
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   customer_ID  924621 non-null  object
 1   pred         924621 non-null  object
dtypes: object(2)
memory usage: 21.2+ MB


In [56]:
df_final_sub.pred.nunique()

4

In [57]:
df_final_sub.pred= df_final_sub.pred.astype (float)

In [58]:
df_final_sub.pred= df_final_sub.pred.astype ('Int64')

In [59]:
df_final_sub.pred.value_counts()


0    724481
1    200140
Name: pred, dtype: Int64

In [60]:
df_final_sub.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 924621 entries, 8 to 11363783
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   customer_ID  924621 non-null  object
 1   pred         924621 non-null  Int64 
dtypes: Int64(1), object(1)
memory usage: 22.0+ MB


In [61]:

df_final_sub.rename(columns = {'pred':'prediction'}, inplace = True)

In [62]:
df_final_sub.to_csv("submission.csv",header=True,index=False)